language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - travis/travis_${TRAVIS_OS_NAME}.sh

before_script:
  - premake4 gmake

script:
  - make -C Build config=release
  - make #clang
