language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes "ppa:codegear/release"
  - sudo apt-get update
  - sudo apt-get --yes install premake4
  
install:
  - sudo pip install cpp-coveralls --use-mirrors

before_script:
  - premake4 gmake

script:
  - make -C Build config=release
  - make #clang
  - make -C Build config=gcov
