language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes "ppa:codegear/release"
  - sudo apt-get update
  - sudo apt-get --yes install premake4
  - git clone https://github.com/jaylyerly/cpp-coveralls.git
  - cd cpp-coveralls
  - sudo python setup.py install 
  - cd ..
  
before_script:
  - premake4 gmake

script:
  - make -C Build config=release
  - make #clang
  - make -C Build config=gcov

after_success:
  - coveralls --verbose --e test --e msinttypes --e Catch --e picojson
